import { ScrollView, Pressable, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import { Image } from 'expo-image';
import { theme } from '../src/theme';

const zoom = ['Mission','Workstream','Task','Agent','Action','Evidence'];
const agents = [['Data Analysis Agent','Q4 report metrics','running'],['Research Agent','Competitor research','running'],['Judge','Independent verification','idle']];

export default function SpaceScreen() {
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{padding:18,gap:18,backgroundColor:theme.canvas}}>
    <View style={{gap:4}}><Text selectable style={{fontSize:30,fontWeight:'760',letterSpacing:-1,color:theme.text}}>Space</Text><Text selectable style={{fontSize:12,lineHeight:18,color:theme.text3}}>Live work arranged around intent, context and attention.</Text></View>
    <View style={{gap:8}}><Text selectable style={{fontSize:10,fontWeight:'700',letterSpacing:1,color:theme.text3}}>Semantic zoom</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:6}}>{zoom.map((item,index)=><Pressable key={item} onPress={()=>Haptics.selectionAsync()} style={{paddingHorizontal:10,paddingVertical:8,borderRadius:10,borderCurve:'continuous',backgroundColor:index===0?theme.text:theme.surface}}><Text selectable style={{fontSize:11,fontWeight:'650',color:index===0?theme.canvas:theme.text2}}>{item}</Text></Pressable>)}</ScrollView></View>
    <View style={{gap:10,padding:14,borderWidth:1,borderColor:theme.border,borderRadius:18,borderCurve:'continuous',backgroundColor:theme.canvas}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><View style={{gap:3}}><Text selectable style={{fontSize:10,color:theme.text3}}>MISSION</Text><Text selectable style={{fontSize:17,fontWeight:'720',color:theme.text}}>Q4 Business Analysis</Text></View><Text selectable style={{fontSize:12,fontVariant:['tabular-nums'],color:theme.text2}}>65%</Text></View><View style={{height:4,borderRadius:4,backgroundColor:theme.surface,overflow:'hidden'}}><View style={{width:'65%',height:4,borderRadius:4,backgroundColor:theme.accent}}/></View><Text selectable style={{fontSize:12,lineHeight:18,color:theme.text2}}>Analysis is live. Evidence stays attached while the workspace reorganizes around the current trajectory.</Text></View>
    <View style={{gap:8}}><Text selectable style={{fontSize:10,fontWeight:'700',letterSpacing:1,color:theme.text3}}>Presence</Text>{agents.map(([name,task,state])=><Pressable key={name} onPress={()=>Haptics.selectionAsync()} style={{minHeight:58,borderTopWidth:1,borderTopColor:theme.border,flexDirection:'row',alignItems:'center',gap:10}}><View style={{width:30,height:30,borderRadius:15,borderCurve:'continuous',backgroundColor:state==='running'?'#E9F8F1':theme.surface,alignItems:'center',justifyContent:'center'}}><Image source={`sf:${state==='running'?'bolt.fill':'circle.dotted'}`} style={{width:14,height:14,tintColor:state==='running'?theme.success:theme.text3}}/></View><View style={{flex:1,gap:2}}><Text selectable style={{fontWeight:'650',color:theme.text}}>{name}</Text><Text selectable style={{fontSize:10,color:theme.text3}}>{task}</Text></View><Text selectable style={{fontSize:10,color:theme.text3}}>{state}</Text></Pressable>)}</View>
    <Pressable onPress={()=>Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)} style={{minHeight:48,borderRadius:14,borderCurve:'continuous',backgroundColor:theme.text,alignItems:'center',justifyContent:'center'}}><Text selectable style={{fontWeight:'700',color:theme.canvas}}>Follow agent</Text></Pressable>
  </ScrollView>;
}
