import test from 'node:test';
import assert from 'node:assert/strict';
import { createCapabilityRegistry } from '../src/federation/capability-registry.mjs';
import { resolveUniversalIntent } from '../src/composer/universal-resolver.mjs';
function registry(granted=[]){const r=createCapabilityRegistry({resolveGrant:(_s,c)=>granted.includes(c.id)});for(const c of [{id:'skill:research',source:'skills-vault',discoverable:true,tags:['research']},{id:'work:execute',source:'works',discoverable:true,tags:['build','execute']},{id:'agent:delegate',source:'avc',discoverable:true,tags:['delegate']},{id:'artifact:create',source:'avc',discoverable:true,tags:['create']}])r.register(c);return r}
test('universal composer resolves intent to capabilities without granting them',()=>{const p=resolveUniversalIntent({text:'research this and build a prototype',mode:'Build',subject:{id:'human:1'},capabilityRegistry:registry()});assert.ok(p.capabilities.some(x=>x.id==='skill:research'));assert.ok(p.capabilities.some(x=>x.id==='work:execute'));assert.equal(p.executionAllowed,false);assert.equal(p.requiresApproval,true)});
test('explicit grants allow planning but resolver still does not execute',()=>{const p=resolveUniversalIntent({text:'build it',mode:'Build',subject:{id:'human:1'},capabilityRegistry:registry(['work:execute'])});assert.equal(p.executionAllowed,true);assert.equal(p.executed,false)});
test('Research mode never implies runtime execution authority',()=>{const p=resolveUniversalIntent({text:'investigate reliability',mode:'Research',subject:{id:'human:1'},capabilityRegistry:registry(['skill:research'])});assert.equal(p.capabilities.some(x=>x.id==='work:execute'),false);assert.equal(p.executed,false)});
test('context object identities are preserved in resolution',()=>{const p=resolveUniversalIntent({text:'inspect this',mode:'Ask',context:[{graphId:'works:work:w1'}],subject:{id:'human:1'},capabilityRegistry:registry()});assert.deepEqual(p.context,['works:work:w1'])});
test('empty human intent is rejected rather than guessed',()=>assert.throws(()=>resolveUniversalIntent({text:'   ',mode:'Ask',subject:{id:'human:1'},capabilityRegistry:registry()}),/intent text/));
