import test from 'node:test';
import assert from 'node:assert/strict';
import { createFederationKernel } from '../src/federation/federation-kernel.mjs';
import { validateIntegrationManifest } from '../src/federation/integration-manifest.mjs';
import { createEnvelope } from '../src/federation/object-envelope.mjs';
function m(id){return validateIntegrationManifest({schema:'aftergraph.integration/v1',id,repository:`Aftergraph/${id}`,integrationVersion:'1',repositoryRevision:'sha',roles:['projection'],objects:['work'],relations:[],capabilities:[],surfaces:['work'],events:[],reads:['work'],writes:['cancel'],authority:[{owner:id,operations:['cancel']}],evidence:[],health:{kind:'test'},degradedBehavior:{reads:'stale',writes:'block'},compatibility:{mode:'exact-or-declared',supported:['1.x']}})}
test('kernel composes registries without creating a new canonical owner',()=>{const k=createFederationKernel();k.registerIntegration(m('works'));k.setIntegrationState('works','current');const o=createEnvelope({sourceIntegration:'works',type:'work',canonicalId:'w1',canonicalOwner:'works',status:'RUNNING',freshness:'current',payload:{},sourceRevision:'sha',authority:[{owner:'works',operations:['cancel']}]});k.reconcile('works',{objects:[o]});assert.equal(k.object('works:work:w1').canonicalOwner,'works')});
test('kernel remains operational when an unrelated integration is unavailable',()=>{const k=createFederationKernel();k.registerIntegration(m('works'));k.registerIntegration(m('isr'));k.setIntegrationState('works','current');k.setIntegrationState('isr','unavailable');assert.equal(k.integration('works').state,'current');assert.equal(k.integration('isr').state,'unavailable')});
test('surface registration is presentation metadata only',()=>{const k=createFederationKernel();const s=k.registerSurface({id:'work-detail',sourceIntegration:'works',objectTypes:['work'],renderer:'work'});assert.equal(s.authority,'none')});
test('consequential write routes to canonical authority adapter and ends resyncing',async()=>{const states=[];const k=createFederationKernel({adapters:{works:{write:async(op,input)=>({op,input,accepted:true})}}});k.registerIntegration(m('works'));k.setIntegrationState('works','current');const o=createEnvelope({sourceIntegration:'works',type:'work',canonicalId:'w1',canonicalOwner:'works',status:'RUNNING',freshness:'current',payload:{},sourceRevision:'sha',authority:[{owner:'works',operations:['cancel']}]});const r=await k.write({object:o,operation:'cancel',input:{reason:'human'},onUiState:x=>states.push(x)});assert.equal(r.accepted,true);assert.deepEqual(states,['submitted','resyncing'])});
test('stale authority blocks consequential writes',async()=>{const k=createFederationKernel({adapters:{works:{write:async()=>({})}}});k.registerIntegration(m('works'));k.setIntegrationState('works','stale');const o=createEnvelope({sourceIntegration:'works',type:'work',canonicalId:'w1',canonicalOwner:'works',status:'RUNNING',freshness:'stale',payload:{},sourceRevision:'sha',authority:[{owner:'works',operations:['cancel']}]});await assert.rejects(()=>k.write({object:o,operation:'cancel',input:{}}),/not current/)});
