import test from 'node:test';
import assert from 'node:assert/strict';
import { createIntegrationRegistry } from '../src/federation/integration-registry.mjs';
import { createObjectGraph } from '../src/federation/object-graph.mjs';
import { createEvidenceGraph } from '../src/federation/evidence-graph.mjs';
import { createCapabilityRegistry } from '../src/federation/capability-registry.mjs';
import { createFederationReconciler } from '../src/federation/reconciler.mjs';
import { validateIntegrationManifest } from '../src/federation/integration-manifest.mjs';
import { createEnvelope } from '../src/federation/object-envelope.mjs';
function manifest(id){return validateIntegrationManifest({schema:'aftergraph.integration/v1',id,repository:`Aftergraph/${id}`,integrationVersion:'1',repositoryRevision:'sha',roles:['projection'],objects:[],relations:[],capabilities:[],surfaces:[],events:[],reads:[],writes:[],authority:[],evidence:[],health:{kind:'test'},degradedBehavior:{reads:'stale',writes:'block'},compatibility:{mode:'exact-or-declared',supported:['1.x']}})}
function setup(){const registry=createIntegrationRegistry();registry.register(manifest('works'));registry.register(manifest('isr'));registry.setState('works','current');registry.setState('isr','current');return {registry,objects:createObjectGraph(),evidence:createEvidenceGraph(),capabilities:createCapabilityRegistry()}}
test('BackgroundSyncNeverStealsHumanNavigation',()=>{const d=setup();const human={activeDomain:'chat',activeConversationId:'c1',activeSpaceId:'s1',composerDraft:'hello',theme:'dark'};const r=createFederationReconciler({...d,getHumanState:()=>human});r.reconcile('works',{objects:[]});assert.deepEqual(human,{activeDomain:'chat',activeConversationId:'c1',activeSpaceId:'s1',composerDraft:'hello',theme:'dark'})});
test('reconcile projects objects and evidence without changing canonical owner',()=>{const d=setup();const r=createFederationReconciler({...d});const obj=createEnvelope({sourceIntegration:'works',type:'work',canonicalId:'w1',canonicalOwner:'works',status:'RUNNING',freshness:'current',payload:{},sourceRevision:'sha'});r.reconcile('works',{objects:[obj],evidence:[{id:'works:e1',owner:'works',class:'execution',method:'verifier'}]});assert.equal(d.objects.get('works:work:w1').canonicalOwner,'works');assert.equal(d.evidence.getEvidence('works:e1').owner,'works')});
test('MissingIntegrationLeavesUnaffectedDomainsOperational',()=>{const d=setup();d.registry.setState('isr','unavailable');const r=createFederationReconciler({...d});const obj=createEnvelope({sourceIntegration:'works',type:'work',canonicalId:'w1',canonicalOwner:'works',status:'RUNNING',freshness:'current',payload:{},sourceRevision:'sha'});assert.doesNotThrow(()=>r.reconcile('works',{objects:[obj]}));assert.equal(d.objects.get(obj.graphId).status,'RUNNING')});
test('unreadable integration cannot inject fresh projection',()=>{const d=setup();d.registry.setState('works','unavailable');const r=createFederationReconciler({...d});assert.throws(()=>r.reconcile('works',{objects:[]}),/not readable/)});
test('projection from stale integration is forced stale',()=>{const d=setup();d.registry.setState('works','stale');const r=createFederationReconciler({...d});const obj=createEnvelope({sourceIntegration:'works',type:'work',canonicalId:'w1',canonicalOwner:'works',status:'RUNNING',freshness:'current',payload:{},sourceRevision:'sha'});r.reconcile('works',{objects:[obj]});assert.equal(d.objects.get(obj.graphId).freshness,'stale')});
