import test from 'node:test';
import assert from 'node:assert/strict';
import { createNowProjection } from '../src/now/now-projection.mjs';
function o(graphId,type,status,sourceIntegration,freshness='current',payload={}){return {graphId,type,status,sourceIntegration,canonicalOwner:sourceIntegration,freshness,payload}}
test('NOW combines active work, needs-you, research, incidents and outcomes without changing ownership',()=>{const p=createNowProjection({objects:[o('works:work:w1','work','RUNNING','works','current',{title:'Deploy'}),o('tg:approval:a1','approval','pending','trust-gateway'),o('isr:claim:c1','claim','validated','isr','current',{title:'Claim'}),o('avc:incident:i1','incident','open','avc'),o('works:outcome:o1','outcome','verified','works')]});assert.equal(p.activeWork[0].canonicalOwner,'works');assert.equal(p.needsYou[0].canonicalOwner,'trust-gateway');assert.equal(p.research[0].canonicalOwner,'isr');assert.equal(p.incidents[0].canonicalOwner,'avc');assert.equal(p.outcomes[0].canonicalOwner,'works')});
test('NOW never labels stale object as current',()=>{const p=createNowProjection({objects:[o('works:work:w1','work','RUNNING','works','stale')]});assert.equal(p.activeWork[0].freshness,'stale');assert.equal(p.activeWork[0].current,false)});
test('NOW reports partial federation coverage explicitly',()=>{const p=createNowProjection({objects:[],integrations:[{manifest:{id:'works'},state:'current'},{manifest:{id:'isr'},state:'unavailable'}]});assert.equal(p.coverage.complete,false);assert.deepEqual(p.coverage.unavailable,['isr'])});
test('terminal work is not active work',()=>{const p=createNowProjection({objects:[o('works:work:w1','work','VERIFIED','works'),o('works:work:w2','work','FAILED','works')]});assert.equal(p.activeWork.length,0)});
test('approval must be pending or needs-input to appear in Needs You',()=>{const p=createNowProjection({objects:[o('tg:approval:a1','approval','approved','trust-gateway'),o('tg:approval:a2','approval','pending','trust-gateway')]});assert.deepEqual(p.needsYou.map(x=>x.graphId),['tg:approval:a2'])});
