import test from 'node:test';
import assert from 'node:assert/strict';
import { graphId, createEnvelope } from '../src/federation/object-envelope.mjs';
import { createObjectGraph, validateRelation } from '../src/federation/object-graph.mjs';

test('same canonical object has stable graph identity across surfaces',()=>{assert.equal(graphId('works','work','wrk_1'),'works:work:wrk_1');assert.equal(graphId('works','work','wrk_1'),graphId('works','work','wrk_1'))});
test('WorkItem and Work cannot collide',()=>assert.notEqual(graphId('wi','work_item','123'),graphId('works','work','123')));
test('graph id segments reject colon ambiguity',()=>assert.throws(()=>graphId('works','work','bad:id'),/colon-free/));
test('envelope preserves canonical owner and source revision',()=>{const e=createEnvelope({sourceIntegration:'works',type:'work',canonicalId:'wrk_1',canonicalOwner:'works',status:'running',payload:{title:'A'},sourceRevision:'sha1'});assert.equal(e.graphId,'works:work:wrk_1');assert.equal(e.canonicalOwner,'works');assert.equal(e.sourceRevision,'sha1');assert.equal(Object.isFrozen(e),true)});
test('relation requires explicit source provenance',()=>assert.throws(()=>validateRelation({type:'fulfills',from:'a',to:'b'}),/sourceIntegration/));
test('unknown irreversible semantics are rejected',()=>assert.throws(()=>validateRelation({type:'becomes_authority',from:'a',to:'b',sourceIntegration:'ui'}),/unknown relation/));
test('object graph returns relation-filtered neighbors without mutating payloads',()=>{const g=createObjectGraph();const a=createEnvelope({sourceIntegration:'wi',type:'work_item',canonicalId:'1',canonicalOwner:'wi',status:'open',payload:{title:'candidate'},sourceRevision:'a'});const b=createEnvelope({sourceIntegration:'works',type:'work',canonicalId:'2',canonicalOwner:'works',status:'running',payload:{title:'work'},sourceRevision:'b'});g.upsert(a);g.upsert(b);g.relate({type:'promoted_to',from:a.graphId,to:b.graphId,sourceIntegration:'wi'});assert.equal(g.neighbors(a.graphId,'promoted_to')[0].graphId,b.graphId);assert.equal(g.get(a.graphId).payload.title,'candidate')});
test('cross tenant relation fails closed when tenant ids conflict',()=>{const g=createObjectGraph();const a=createEnvelope({sourceIntegration:'wi',type:'work_item',canonicalId:'1',canonicalOwner:'wi',tenantId:'t1',status:'open',payload:{},sourceRevision:'a'});const b=createEnvelope({sourceIntegration:'works',type:'work',canonicalId:'2',canonicalOwner:'works',tenantId:'t2',status:'running',payload:{},sourceRevision:'b'});g.upsert(a);g.upsert(b);assert.throws(()=>g.relate({type:'related_to',from:a.graphId,to:b.graphId,sourceIntegration:'wi'}),/cross-tenant/)});
test('cross tenant relation fails closed when one tenant is missing',()=>{const g=createObjectGraph();const a=createEnvelope({sourceIntegration:'wi',type:'work_item',canonicalId:'1',canonicalOwner:'wi',tenantId:'t1',status:'open',payload:{},sourceRevision:'a'});const b=createEnvelope({sourceIntegration:'works',type:'work',canonicalId:'2',canonicalOwner:'works',tenantId:null,status:'running',payload:{},sourceRevision:'b'});g.upsert(a);g.upsert(b);assert.throws(()=>g.relate({type:'related_to',from:a.graphId,to:b.graphId,sourceIntegration:'wi'}),/cross-tenant/)});
